python main.py --priority_error_distance 0.1 --priority_error_rate 0.1
python main.py --priority_error_distance 0.2 --priority_error_rate 0.2
python main.py --priority_error_distance 0.3 --priority_error_rate 0.3
python main.py --priority_error_distance 0.4 --priority_error_rate 0.4
python main.py --priority_error_distance 0.5 --priority_error_rate 0.5
python main.py --priority_error_distance 0.6 --priority_error_rate 0.6
python main.py --priority_error_distance 0.7 --priority_error_rate 0.7
python main.py --priority_error_distance 0.8 --priority_error_rate 0.8
python main.py --priority_error_distance 0.9 --priority_error_rate 0.9
python main.py --priority_error_distance 1.0 --priority_error_rate 1.0
